name: Playwright and API Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка Node.js для Playwright и сервера
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Установка зависимостей Node.js (для Playwright и сервера)
      - name: Install Node.js dependencies
        run: npm ci

      # Установка браузеров для Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Запуск сервера Express (нужно запустить сервер до тестов)
      - name: Start Express server
        run: |
          nohup node server.js &

      # Запуск тестов Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # Установка Python для API тестов
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Установка зависимостей для Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Копирование базы данных SQLite на сервер CI
      - name: Copy SQLite database
        run: |
          cp ./my_database.db ./my_database.db

      # Запуск тестов API с Pytest
      - name: Run API tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Загрузка отчёта о Playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
