name: Playwright and API Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installing Node.js for Playwright and express-server
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Installing dependencies Node.js (for Playwright and express-server)
      - name: Install Node.js dependencies
        run: npm ci

      # Installing browsers for Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Starting Express server
      - name: Start Express server
        run: |
          nohup node local_server.js &

      # Running Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Installing Python for API tests
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Installing Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Running API tests with Pytest
      - name: Run API tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Uploading report of Playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
